spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examplesdb?useUnicode=true&lacalTimezone=Aisa/Seoul
    username: root
    password: root1234
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html  #.jsp로 변경하면 jsp파일을 템플릿으로 사용한다.
